services:
  - type: web
    name: fundhub-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: STELLAR_NETWORK
        value: testnet
      - key: STELLAR_HORIZON_URL
        value: https://horizon-testnet.stellar.org
      - key: SOROBAN_RPC_URL
        value: https://soroban-testnet.stellar.org
      - key: PLATFORM_WALLET_PUBLIC_KEY
        sync: false
      - key: RUST_LOG
        value: info
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    autoDeploy: true
    branch: main
